# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rray.proto\"*\n\x0b\x44oubleArray\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\"\'\n\x08IntArray\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'array_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOUBLEARRAY._serialized_start=15
  _DOUBLEARRAY._serialized_end=57
  _INTARRAY._serialized_start=59
  _INTARRAY._serialized_end=98
# @@protoc_insertion_point(module_scope)
