# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import array_pb2 as array__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x1a\x0b\x61rray.proto\"J\n\x10VariableMetaData\x12\r\n\x05input\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x03(\x03\x12\r\n\x05units\x18\x04 \x01(\t\"\xe4\x01\n\tVariables\x12.\n\ncontinuous\x18\x01 \x03(\x0b\x32\x1a.Variables.ContinuousEntry\x12*\n\x08\x64iscrete\x18\x02 \x03(\x0b\x32\x18.Variables.DiscreteEntry\x1a?\n\x0f\x43ontinuousEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.DoubleArray:\x02\x38\x01\x1a:\n\rDiscreteEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.IntArray:\x02\x38\x01\"<\n\x08Partials\x12\t\n\x01\x66\x18\x01 \x03(\t\x12\t\n\x01x\x18\x02 \x03(\t\x12\x1a\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x0c.DoubleArrayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VARIABLES_CONTINUOUSENTRY._options = None
  _VARIABLES_CONTINUOUSENTRY._serialized_options = b'8\001'
  _VARIABLES_DISCRETEENTRY._options = None
  _VARIABLES_DISCRETEENTRY._serialized_options = b'8\001'
  _VARIABLEMETADATA._serialized_start=27
  _VARIABLEMETADATA._serialized_end=101
  _VARIABLES._serialized_start=104
  _VARIABLES._serialized_end=332
  _VARIABLES_CONTINUOUSENTRY._serialized_start=209
  _VARIABLES_CONTINUOUSENTRY._serialized_end=272
  _VARIABLES_DISCRETEENTRY._serialized_start=274
  _VARIABLES_DISCRETEENTRY._serialized_end=332
  _PARTIALS._serialized_start=334
  _PARTIALS._serialized_end=394
# @@protoc_insertion_point(module_scope)
